"""add_flow_params_to_schedules

Revision ID: 14d1c29e0c79
Revises: 6bf8b3bc2375
Create Date: 2025-01-07 15:09:49.899856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14d1c29e0c79'
down_revision: Union[str, None] = '6bf8b3bc2375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flows', 'user_id')
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('logs_task_id_fkey', 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'tasks', ['task_id'], ['id'])
    op.add_column('schedules', sa.Column('flow_params', sa.JSON(), nullable=True))
    op.alter_column('tasks', 'flow_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'flow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('schedules', 'flow_params')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key('logs_task_id_fkey', 'logs', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('logs', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('flows', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
