"""Add schedule_type and schedule_expr columns

Revision ID: 68c30d8e328d
Revises: e6dd44e1aa45
Create Date: 2025-01-24 18:28:49.348774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c30d8e328d'
down_revision: Union[str, None] = 'e6dd44e1aa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_components', 'flow_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('flows', 'folder_id')
    op.add_column('schedules', sa.Column('schedule_type', sa.String(), nullable=False))
    op.add_column('schedules', sa.Column('schedule_expr', sa.String(), nullable=False))
    op.add_column('schedules', sa.Column('flow_params', sa.JSON(), nullable=True))
    op.add_column('schedules', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('schedules', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('schedules', 'cron_expression')
    op.drop_column('schedules', 'enabled')
    op.add_column('tasks', sa.Column('input_data', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'input_data')
    op.add_column('schedules', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('cron_expression', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('schedules', 'status')
    op.drop_column('schedules', 'next_run_at')
    op.drop_column('schedules', 'flow_params')
    op.drop_column('schedules', 'schedule_expr')
    op.drop_column('schedules', 'schedule_type')
    op.add_column('flows', sa.Column('folder_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('flow_components', 'flow_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
