
"""fix task model inheritance

Revision ID: 65c36ca5a427
Revises: merge_timestamp_migrations
Create Date: 2025-02-10 04:57:16.191173+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65c36ca5a427'
down_revision: Union[str, None] = 'merge_timestamp_migrations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'flow_raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('fk_workflows_workflow_source_id', 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'workflow_sources', ['workflow_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key('fk_workflows_workflow_source_id', 'workflows', 'workflow_sources', ['workflow_source_id'], ['id'], ondelete='SET NULL')
    op.alter_column('workflows', 'flow_raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


